title: sumeetv
author: Sumeet Vaidya
email: me@sumeetv.com
description: > # this means to ignore newlines until "baseurl:"
  A testing site and a chance to check out GitHub labs.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
